cd /var/www/ftp

sudo umount -l apache/
sudo umount -l CTAN/
sudo umount -l archlinux/
sudo umount -l centos/
sudo umount -l CRAN/
sudo umount -l debian/
sudo umount -l debian-cd/
sudo umount -l deb-multimedia/
sudo umount -l elvish/
sudo umount -l gentoo/
sudo umount -l jenkins/
sudo umount -l kali/
sudo umount -l kali-images/
sudo umount -l mariadb/
sudo umount -l opensuse/
sudo umount -l postgresql/
sudo umount -l repoforge/
sudo umount -l ubuntu
sudo umount -l ubuntu-releases/
sudo umount -l videolan-ftp/
sudo umount -l vim/
sudo umount -l pub/vim/
sudo umount -l zabbix/

sudo umount -l anaconda/
sudo umount -l docker-ce/
sudo umount -l mongodb/
sudo umount -l mysql/
sudo umount -l node/
sudo umount -l pritunl/
sudo umount -l virtualbox/
sudo umount -l zerotier/
sudo umount -l ruby
sudo umount -l pypi/

sudo umount -l alpine/
sudo umount -l archlinuxarm/
sudo umount -l archlinuxcn/
sudo umount -l centos-altarch/
sudo umount -l ceph/
sudo umount -l CPAN
sudo umount -l cygwin/
sudo umount -l deepin/
sudo umount -l deepin-cd/
sudo umount -l eclipse/
sudo umount -l gimp/
sudo umount -l gnome/
sudo umount -l gnu/
sudo umount -l homebrew-bottles/
sudo umount -l iina/
sudo umount -l kde/
sudo umount -l kernel/
sudo umount -l lede
sudo umount -l libreoffice/
sudo umount -l linuxmint/
sudo umount -l manjaro/
sudo umount -l manjaro-cd/
sudo umount -l msys2/
sudo umount -l openwrt/
sudo umount -l parrot/
sudo umount -l putty/
sudo umount -l raspbian/
sudo umount -l RFCs/
sudo umount -l rubygems/

sudo umount -l anthon/
sudo umount -l epel/
sudo umount -l fedora/
sudo umount -l linuxmint-cd/
sudo umount -l macports/

sudo umount -l /home/mirror/nfs
sudo umount -l /home/mirror/nfs2